spring.application.name=apiIA


server.servlet.context-path=/api
#server.port=9191

#OPENAI
spring.ai.openai.api-key=${GCP_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
# Altere para o modelo de 8B ou 3B se estiver usando o starter do Groq/OpenAI
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile


#spring.datasource.url=jdbc:postgresql://localhost:5434/bd-agente-ia
#spring.datasource.username=postgres
#spring.datasource.password=250499
#spring.datasource.driver-class-name=org.postgresql.Driver

## ? ESSENCIAL PARA SUPABASE
#spring.jpa.properties.hibernate.jdbc.batch_size=0
#spring.jpa.properties.hibernate.jdbc.use_get_generated_keys=true
#spring.jpa.properties.hibernate.jdbc.prepared_statement_cache_size=0
#spring.jpa.properties.hibernate.jdbc.prepared_statement_cache_sql_limit=0
#spring.jpa.properties.hibernate.connection.release_mode=after_statement
#spring.jpa.properties.hibernate.jdbc.use_reflection_optimizer=false
#
## ? DESLIGA prepared statements
#spring.datasource.hikari.data-source-properties.prepareThreshold=0

spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.mntvremvifgvbpasagsm
spring.datasource.password=BenitoIA20.26*
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA (Hibernate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

cobol.fontes.path=C:/Users/jorge.prado/Downloads/pessoais/Projetos/n8n/fontes

jwt.secret=5c7ff1d3-a068-480a-9b5c-c5f1ee2797d8-d7bf462b-a9b3-4d44-8a8e-787e340d4460-2400230c-df81-4711-8ff5-7f1cf94d53dd